### ISSUE TITLE
MAM works, but Carbon wont

### ISSUE THREAD

**Issue by denser** [jappix/jappix#590]
I try to setup Jappix and Metronome as described such lovely ally, but w/o success.
I need to use Windows AD, so i use ejabberd and get luck with it(shared roster, groups etc.) all works BUT.

I test it with Gajim and can see previously written messages, even from other device.
In Jappix i don see them, but if i look at browser console(f12 in Opera or Chrome) then i can see BOSH xml with recivied MAM messages.

So, what if Jappix have wrong analitycs for MAM? It think that messages come from server not for this user or smth? I dont get it, try to seek in js to realize where it goes but miss something, please help me.

**Comment by denser** [comment]
If there need screens i can handle it.

**Comment by valeriansaliou** [comment]
Hi, Jappix is not maintained anymore.

**Comment by denser** [comment]
I know, i just need help with this issue.

**Comment by maranda** [comment]
You just need a new client not Jappix, it won't work with Metronome (or ejabberd?) because it uses the old prototype XEP of MAM which is neither compliant to current standard or even past MAM revisions. There're plenty of choices beside Jappix like Converse-js, JSXC, Movim etc... one would like to know why you want to stick with Jappix which is obsolete and most probably has some vulnerabilities by now.
